name: CI

env:
    AWS_REGION: eu-west-3

on:
    push:
        branches:
            - '*'
    pull_request:
        branches:
            - '*'
    workflow_dispatch:

jobs:
    quality-check:
        runs-on: ubuntu-latest
        timeout-minutes: 20
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - id: install-aws-cli
              uses: unfor19/install-aws-cli-action@v1.0.3
              with:
                  version: 2
                  verbose: false
                  arch: amd64
                  rootdir: ''
                  workdir: ''

            - name: Connect to private CodeArtifact repository
              run: |
                  sh ./.shell/initAWS.sh bpartners ${{ secrets.AWS_ACCESS_KEY_ID }} ${{ secrets.AWS_SECRET_KEY }} ${{ env.AWS_REGION }}
                  sh ./.shell/initNpmrc.sh bpartners annotator-imagery-store npm-bpartners-imagery-app 205205101409

            - name: Run test
              uses: cypress-io/github-action@v6
              with:
                  install-command: npm install --legacy-peer-deps
                  component: true

    style:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 17.x

            - run: npm install --location=global prettier
            - run: prettier --check "src/**/*.{js,ts,tsx}" "./**/*.{json,yml,yaml}"
